spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: org.apache.tomcat.jdbc.pool.DataSource
    url: jdbc:mysql://localhost:3306/Fuliaoyi?useUnicode=true&characterEncoding=utf-8
    username: dev
    password: 111111

mybatis:
  mapper-locations: classpath*:mapper/*.xml

logging:
  config: classpath:logback/logback-console.xml

server:
  port: 8080

app-config:
  sendSMS: true